name: Prepare Clean Merge to Main (Excluding tests/)

on:
  push:
    branches:
      - test

permissions:
  contents: write  # <-- Needed to push new branch

jobs:
  prepare-clean-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: test

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # - name: Install test dependencies
      #   run: pip install -r requirements-test.txt

      # - name: Run notebook tests
      #   run: pytest -s -v tests/test_notebooks.py

      - name: Create cleaned commit (without tests/)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -B clean-merge
          git rm -r --cached tests || echo "No tests/ to remove"
          git commit -m "Prepare clean commit without tests/" || echo "Nothing to commit"

      - name: Push clean-merge branch
        run: git push origin clean-merge --force
