name: Auto Squash Merge from Test to Main Without Tests

on:
  push:
    branches:
      - test

jobs:
  squash-merge:
    runs-on: ubuntu-latest

    env:
      GIT_AUTHOR_NAME: GitHub Actions
      GIT_AUTHOR_EMAIL: actions@github.com
      GIT_COMMITTER_NAME: GitHub Actions
      GIT_COMMITTER_EMAIL: actions@github.com
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: test

      - name: Run tests
        run: |
          pip install -r requirements-test.txt
          pytest -s -v tests/test_notebooks.py

      - name: Prepare clean merge using git worktree
        run: |
          # Add main branch as a separate worktree
          git worktree add ../merge-main main
          cd ../merge-main

          # Remove tests/ folder from index only (not deleting it)
          git rm -r --cached tests || echo "tests/ not present in main"

          # Merge test branch as squash
          git merge --squash ../${{ github.workspace }}

          # Commit the squash merge
          git commit -m "Automated squash merge from test (excluding tests/)"

          # Push changes to main
          git push origin main

      - name: Cleanup worktree
        run: git worktree remove ../merge-main --force
