name: Prepare Clean Merge to Main (Excluding tests/)

on:
  push:
    branches:
      - test

permissions:
  contents: write  # <-- Needed to push new branch

jobs:
  prepare-clean-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: test

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # - name: Install test dependencies
      #   run: pip install -r requirements-test.txt

      # - name: Run notebook tests
      #   run: pytest -s -v tests/test_notebooks.py

      - name: Create clean commit without tests/
        run: |
          git checkout --orphan clean-merge
          git reset
          git add .
          git rm -r --cached tests || echo "tests/ not present"
          git commit -m "Clean commit without tests/"
          git push -f origin clean-merge


      - name: Push clean-merge branch
        run: git push origin clean-merge --force
