name: Auto Squash Merge from Test to Main Without Tests

on:
  push:
    branches:
      - test

permissions:
  contents: write  # Required to push to 'main'

jobs:
  squash-merge:
    runs-on: ubuntu-latest

    env:
      GIT_AUTHOR_NAME: GitHub Actions
      GIT_AUTHOR_EMAIL: actions@github.com
      GIT_COMMITTER_NAME: GitHub Actions
      GIT_COMMITTER_EMAIL: actions@github.com

    steps:
      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: test

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements-test.txt

      - name: Run notebook tests
        run: pytest -s -v tests/test_notebooks.py

      - name: Prepare clean merge without tests/
        run: |
          # Create a temporary branch to stage the squash
          git checkout -b temp-clean-merge

          # Remove tests folder from the index (not from disk)
          git rm -r --cached tests || echo "tests/ folder not present"
          git commit -m "Prepare merge: remove tests/ folder"

      - name: Checkout main and perform squash merge
        run: |
          git checkout main
          git merge --squash temp-clean-merge
          git commit -m "Auto squash merge from test (excluding tests/)"
          git push origin main
