name: Python Notebook Testing

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.ipynb'
      - 'requirements-test.txt'
      - 'environment.yml'
      - 'tests/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  test-all-if-reqs-changed:
    if: |
      contains(github.event.pull_request.changed_files, 'requirements.txt')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'requirements-test.txt'
      - run: pip install -r requirements-test.txt
    
      - run: pip cache dir

      - name: Pre-cache Cartopy shapefiles
        run: |
          python -c "
          import cartopy
          import cartopy.feature as cfeature
          _ = cfeature.COASTLINE.geometries()
          _ = cfeature.BORDERS.geometries()
          _ = cfeature.LAND.geometries()
          "
      - name: Pre-cache Cartopy shapefiles
        run: |
          python -c "
          import cartopy.feature as cfeature
          list(cfeature.COASTLINE.geometries())
          list(cfeature.BORDERS.geometries())
          "
      
      - name: Cache Cartopy shapefiles
        uses: actions/cache@v4
        with:
          path: ~/.local/share/cartopy
          key: cartopy-cache-v1

      - name: Run all tests
        run: pytest

  test-modified-notebooks:
    if: |
      !contains(github.event.pull_request.changed_files, 'requirements.txt')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'requirements-test.txt'
      - run: pip install -r requirements-test.txt
    
      - run: pip cache dir

      - name: Pre-cache Cartopy shapefiles
        run: |
          python -c "
          import cartopy
          import cartopy.feature as cfeature
          _ = cfeature.COASTLINE.geometries()
          _ = cfeature.BORDERS.geometries()
          _ = cfeature.LAND.geometries()
          "
      - name: Pre-cache Cartopy shapefiles
        run: |
          python -c "
          import cartopy.feature as cfeature
          list(cfeature.COASTLINE.geometries())
          list(cfeature.BORDERS.geometries())
          "
      
      - name: Cache Cartopy shapefiles
        uses: actions/cache@v4
        with:
          path: ~/.local/share/cartopy
          key: cartopy-cache-v1

      - name: Detect changed notebooks
        id: changed
        run: |
          notebooks=$(git diff --name-only origin/main...HEAD | grep ".ipynb" | xargs)
          echo "NOTEBOOKS=$notebooks" >> $GITHUB_ENV

      - name: Run notebook tests
        if: env.NOTEBOOKS != ''
        run: |
          pytest -s -v tests/test_notebooks.py
        
      - name: Debug with tmate if test fails
        if: failure()
        uses: mxschmitt/action-tmate@v3
