name: Python Notebook Testing

on:
  pull_request:
    branches: [main]
    paths:
      - '**.ipynb'
      - 'requirements-test.txt'
      - 'environment.yml'
      - 'tests/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  test-modified-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'requirements-test.txt'

      - name: Install test dependencies
        run: pip install -r requirements-test.txt


      - name: Run notebook tests
        run: pytest -s -v tests/test_notebooks.py

      - name: Debug with tmate if test fails
        if: failure()
        uses: mxschmitt/action-tmate@v3
