name: Python Notebook Testing

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.ipynb'
      - 'requirements-test.txt'
      - 'environment.yml'
      - 'tests/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  test-all-if-reqs-changed:
    if: contains(github.event.pull_request.changed_files, 'requirements-test.txt')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'requirements-test.txt'

      - name: Install dependencies
        run: pip install -r requirements-test.txt

      - run: pip cache dir

      - name: Pre-cache Cartopy shapefiles
        run: |
          python -c "
          import cartopy
          import cartopy.feature as cfeature
          _ = list(cfeature.COASTLINE.geometries())
          _ = list(cfeature.BORDERS.geometries())
          _ = list(cfeature.LAND.geometries())
          "

      - name: Cache Cartopy shapefiles
        uses: actions/cache@v4
        with:
          path: ~/.local/share/cartopy
          key: cartopy-cache-v1

      - name: Run all tests
        run: pytest

  test-modified-notebooks:
    if: |
      !contains(github.event.pull_request.changed_files, 'requirements-test.txt')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'requirements-test.txt'

      - name: Install dependencies
        run: pip install -r requirements-test.txt

      - run: pip cache dir

      - name: Pre-cache Cartopy shapefiles
        run: |
          python -c "
          import cartopy
          import cartopy.feature as cfeature
          _ = list(cfeature.COASTLINE.geometries())
          _ = list(cfeature.BORDERS.geometries())
          _ = list(cfeature.LAKES.geometries())
          _ = list(cfeature.LAND.geometries())
          _ = list(cfeature.OCEAN.geometries())
          _ = list(cfeature.RIVERS.geometries())
          _ = list(cfeature.LAND.geometries())  # Repeats LAND to ensure caching
          _ = list(cfeature.NaturalEarthFeature('physical', 'geography_regions_polys', '50m').geometries())
          "

      - name: Cache Cartopy shapefiles
        uses: actions/cache@v4
        with:
          path: ~/.local/share/cartopy
          key: cartopy-cache-v1

      - name: Detect changed notebooks
        id: changed
        run: |
          git fetch origin main --quiet
          notebooks=$(git diff --name-only origin/main...HEAD -- '*.ipynb' | xargs || true)
          echo "NOTEBOOKS=$notebooks" >> $GITHUB_ENV
          echo "Changed notebooks: $notebooks"

      - name: Run notebook tests
        if: env.NOTEBOOKS != ''
        run: |
          pytest -s -v tests/test_notebooks.py

      - name: Debug with tmate if test fails
        if: failure()
        uses: mxschmitt/action-tmate@v3
